---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    entrypoint: [ "bash", "-c", "((sleep 30 && kafka-topics --create --topic gisa-topic --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:32181)&) && /etc/confluent/docker/run"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
    
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@123"
      MYSQL_DATABASE: "rundeck"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql@123"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./script:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysqlsrv
    depends_on:
      - mysqlsrv
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

  sqoop:
    #image: ghcr.io/kasipavankumar/sqoop-docker:latest
    image: dvoros/sqoop:latest
    depends_on:
      - mysqlsrv
    links:
      - mysqlsrv
    entrypoint: [ "bash", "-c", "((ln -sf /jdbc/mysql-connector-java-5.1.38.jar /usr/local/sqoop/lib/mysql-connector-java-5.1.38.jar && chmod 777 /usr/local/sqoop/lib/mysql-connector-java-5.1.38.jar)&) && tail -f /dev/null"]
    volumes:
      - ./lib:/jdbc

  #rundeck:
  #  image: rundeck/rundeck:3.4.4
  #  links:
  #    - mysqlsrv
  #  environment:
  #      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
  #      RUNDECK_DATABASE_USERNAME: mysql
  #      RUNDECK_DATABASE_PASSWORD: mysql@123
  #      RUNDECK_DATABASE_URL: jdbc:mysql://mysqlsrv/rundeck?autoReconnect=true&useSSL=false
  #  depends_on:
  #    - mysqlsrv
    #volumes:
      #- ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
  #  ports:
  #    - 4440:4440